---
- name: Nextcloud
  hosts: nextcloud
  become: yes
  vars:
    db_name: "dbnextcloud"      # Имя базы данных
    db_user: "pguser"    # Пользователь базы данных
    db_password: "pgpassword"  # Пароль для базы данных
    nextcloud_admin_user: "admin"   # Логин администратора Nextcloud
    nextcloud_admin_password: "admin_password"  # Пароль администратора Nextcloud

  tasks:
    - name: Timezone Moscow
      community.general.timezone:
        name: Europe/Moscow

    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - apache2
          - libapache2-mod-php
          - acl
          - php-curl
          - php-gd
          - php-json
          - php-mbstring
          - php-xml
          - php-zip
          - php-intl
          - php-mysql
          - php-pgsql
          - php-bcmath
          - unzip
          - python3-pip
          - postgresql
          - postgresql-contrib
          - postgresql-all
          - wget
          - bzip2
        state: present

    - name: Install psycopg2
      ansible.builtin.pip:
        extra_args: "--break-system-packages"
        name: psycopg2

    - name: Download and unpack Nextcloud
      ansible.builtin.unarchive:
        dest: "/var/www/html"
        src: "https://download.nextcloud.com/server/releases/latest-30.tar.bz2"
        remote_src: true
        owner: "www-data"
        group: "www-data"
        creates: "/var/www/html/nextcloud"

    - name: Запуск и включение Apache и PostgreSQL
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - postgresql

    - name: Init PostgreSQL user
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        db: "{{ db_name }}"
        role_attr_flags: "CREATEDB,LOGIN"
        state: present

    - name: Init PostgreSQL DB for Nextcloud
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        encoding: "UTF8"
        lc_ctype: "en_US.UTF-8"
        lc_collate: "en_US.UTF-8"
        state: present

    - name: Check if Database is initialized
      stat:
        path: /var/lib/pgsql/14/data/pg_hba.conf
      register: result

    - name: Настройка Apache для Nextcloud
      copy:
        dest: "/etc/apache2/sites-available/nextcloud.conf"
        content: |
          <VirtualHost *:80>
              DocumentRoot "/var/www/html/nextcloud"
              ServerName vvot22.itiscl.ru

              <Directory "/var/www/html/nextcloud">
                  Options FollowSymlinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/vvot22_error.log
              CustomLog ${APACHE_LOG_DIR}/vvot22_access.log combined
          </VirtualHost>
      notify: Перезапуск Apache

    - name: Активация сайта Nextcloud
      file:
        src: "/etc/apache2/sites-available/nextcloud.conf"
        dest: "/etc/apache2/sites-enabled/nextcloud.conf"
        state: link

    - name: Проверка наличия конфигурации Nextcloud
      stat:
        path: /var/www/html/nextcloud/config/config.php
      register: nextcloud_config

    - name: Настройка конфигурации Nextcloud
      shell: |
        cd /var/www/html/nextcloud
        sudo -u www-data php occ maintenance:install \
          --database "pgsql" \
          --database-name "{{ db_name }}" \
          --database-user "{{ db_user }}" \
          --database-pass "{{ db_password }}" \
          --admin-user "{{ nextcloud_admin_user }}" \
          --admin-pass "{{ nextcloud_admin_password }}"
      when: not nextcloud_config.stat.exists

    - name: Добавление домена в trusted_domains
      lineinfile:
        path: /var/www/nextcloud/config/config.php
        regexp: "^\\s*'trusted_domains' =>"
        line: "  'trusted_domains' => array ( 0 => 'localhost', 1 => '158.160.38.199', 2 => 'vvot22.itiscl.ru', 3 => '[2001:db8::1]', ),"
        insertafter: "'instanceid' =>"


  handlers:
    - name: Перезапуск Apache
      service:
        name: apache2
        state: restarted

